#!/usr/bin/env sh

# Get the commit message
COMMIT_MSG=$1

# Get current branch name
BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

# Extract the first complete number after the first "/" in a string
NUMBER_REGEX='^[^/]+/([0-9]+).*'

echo "Branch name: $BRANCH_NAME"
echo "Commit message: $COMMIT_MSG"

# Function to extract number after the first "/"
extract_number() {
    # If number found in branch name
    if [[ $BRANCH_NAME =~ $NUMBER_REGEX ]]; then
        # Extract the issue number from the branch name
        ISSUE_NUMBER=${BASH_REMATCH[1]}
        echo "Issue number: $ISSUE_NUMBER"
        # Add the issue number to the commit message
        sed -i '1s/^/$ISSUE_NUMBER: /' "$COMMIT_MSG"
    else
        echo "No number found in branch name"
    fi
}
