#!/usr/bin/env sh

# Check for eslint
ESLINT="$(git rev-parse --show-toplevel)/frontend/node_modules/.bin/eslint"
if [[ ! -x "$ESLINT" ]]; then
  echo "$ESLINT"
  echo "Please install ESlint (npm i --save --save-exact --dev eslint)"
  exit 1
fi

# Check if there are any staged files
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".tsx\{0,1\}$")
if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

PASS=true

echo "ESLinting Frontend:"

for FILE in $STAGED_FILES
do
  eslint "$FILE"
  
  if [[ "$?" == 0 ]]; then
    echo "ESLint Passed: $FILE"
  else
    echo "ESLint Failed: $FILE"
    exit 1
  fi
done

exit $?