#!/usr/bin/env sh

# This script validates the branch name format before allowing the commit to proceed.
BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
echo "Branch name: $BRANCH_NAME"

## Define the regular expression for branch name validation
# BRANCH_REGEX='^(feat|fix|hotfix|release)\/\d+_.+'
BRANCH_REGEX='feat/21_pre-commit'

## Check if the branch name matches the defined regex
if ! [[ $BRANCH_NAME =~ $BRANCH_REGEX ]]; then
   echo 'Branch name should start with feat/, fix/, hotfix/ or release/'
   echo 'Branch name should then include issue number'
   echo 'Branch name should then include a separator "_" followed by the branch name'
   echo 'Example: feat/142_branch-name' 
   echo 'Rename the branch using "git branch -m new-branch-name" and try again.'
   exit 1
fi