#!/usr/bin/env sh

# This script validates the branch name format before allowing the commit to proceed.
BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

## Define the regular expression for branch name validation
BRANCH_REGEX='^(feat|fix|hotfix|release)/.+'

## Check if the branch name matches the defined regex
if ! [[ $BRANCH_NAME =~ $BRANCH_REGEX ]]; then
   echo "Branch name should start with feat/, fix/, hotfix/ or release/"
   exit 2
fi