# Generated by Django 5.0.4 on 2024-05-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tagName", models.CharField(max_length=50)),
                ("count", models.IntegerField()),
                ("excerptPostId", models.IntegerField(null=True)),
                ("wikiPostId", models.IntegerField(null=True)),
                ("isModeratorOnly", models.BooleanField()),
                ("isRequired", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Posts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("postTypeId", models.IntegerField()),
                ("acceptedAnswerId", models.IntegerField(null=True)),
                ("parentId", models.IntegerField(null=True)),
                ("creationDate", models.DateField()),
                ("deletionDate", models.DateField(null=True)),
                ("score", models.IntegerField()),
                ("viewcount", models.IntegerField(null=True)),
                ("body", models.TextField()),
                ("ownerUserId", models.IntegerField(null=True)),
                ("ownerDisplayName", models.CharField(max_length=255, null=True)),
                ("lastEditorUserId", models.IntegerField(null=True)),
                ("lastEditorDisplayName", models.CharField(max_length=255, null=True)),
                ("lastEditDate", models.DateField(null=True)),
                ("lastActivityDate", models.DateField()),
                ("title", models.CharField(max_length=255)),
                ("answerCount", models.IntegerField(null=True)),
                ("commentCount", models.IntegerField(null=True)),
                ("favoriteCount", models.IntegerField(null=True)),
                ("closedDate", models.DateField(null=True)),
                ("communityOwnedDate", models.DateField(null=True)),
                ("tags", models.ManyToManyField(related_name="posts", to="core.tags")),
            ],
        ),
    ]
