# Generated by Django 5.0.4 on 2024-05-29 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="answerCount",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="posts",
            name="commentCount",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="posts",
            name="favoriteCount",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="posts",
            name="score",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="posts",
            name="tags",
            field=models.ManyToManyField(related_name="tags", to="core.tags"),
        ),
        migrations.AlterField(
            model_name="posts",
            name="viewcount",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="tags",
            name="count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="tags",
            name="isModeratorOnly",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="tags",
            name="isRequired",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255, null=True)),
                ("avatar", models.CharField(max_length=255, null=True)),
                ("bio", models.TextField(max_length=255, null=True)),
                ("reputation", models.IntegerField(default=0, null=True)),
                ("joinDate", models.DateField()),
                ("upVotes", models.IntegerField(default=0, null=True)),
                ("downVotes", models.IntegerField(default=0, null=True)),
                (
                    "edits",
                    models.ManyToManyField(related_name="edits", to="core.posts"),
                ),
                (
                    "posts",
                    models.ManyToManyField(related_name="posts", to="core.posts"),
                ),
                (
                    "private_post",
                    models.ManyToManyField(
                        related_name="private_post", to="core.posts"
                    ),
                ),
                (
                    "savedPosts",
                    models.ManyToManyField(related_name="saved_posts", to="core.posts"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
