# Generated by Django 5.0.4 on 2024-06-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_posts_answercount_alter_posts_commentcount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="posts",
            name="acceptedAnswerId",
        ),
        migrations.RemoveField(
            model_name="posts",
            name="answerCount",
        ),
        migrations.RemoveField(
            model_name="posts",
            name="closedDate",
        ),
        migrations.RemoveField(
            model_name="posts",
            name="commentCount",
        ),
        migrations.RemoveField(
            model_name="posts",
            name="communityOwnedDate",
        ),
        migrations.RemoveField(
            model_name="posts",
            name="creationDate",
        ),
        migrations.RemoveField(
            model_name="posts",
            name="deletionDate",
        ),
        migrations.RemoveField(
            model_name="posts",
            name="favoriteCount",
        ),
        migrations.RemoveField(
            model_name="posts",
            name="lastActivityDate",
        ),
        migrations.RemoveField(
            model_name="posts",
            name="lastEditDate",
        ),
        migrations.RemoveField(
            model_name="posts",
            name="lastEditorDisplayName",
        ),
        migrations.RemoveField(
            model_name="posts",
            name="lastEditorUserId",
        ),
        migrations.RemoveField(
            model_name="posts",
            name="ownerDisplayName",
        ),
        migrations.RemoveField(
            model_name="posts",
            name="parentId",
        ),
        migrations.RemoveField(
            model_name="posts",
            name="postTypeId",
        ),
        migrations.RemoveField(
            model_name="posts",
            name="score",
        ),
        migrations.RemoveField(
            model_name="posts",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="posts",
            name="viewcount",
        ),
        migrations.AddField(
            model_name="posts",
            name="type",
            field=models.CharField(
                choices=[
                    ("argument", "argument"),
                    ("rebuttal", "rebuttal"),
                    ("comment", "comment"),
                ],
                default="argument",
                max_length=10,
            ),
        ),
    ]
