# Generated by Django 5.0.4 on 2024-06-25 14:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_remove_posts_acceptedanswerid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="posts",
            name="createdAt",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="posts",
            name="updatedAt",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
