# Generated by Django 5.0.4 on 2024-06-26 02:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_posts_createdat_posts_updatedat"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Tags",
        ),
    ]
