# Generated by Django 5.0.4 on 2024-07-04 22:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_vote_remove_userprofile_downvotes_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="posts",
            old_name="createdAt",
            new_name="created",
        ),
        migrations.RenameField(
            model_name="posts",
            old_name="updatedAt",
            new_name="updated",
        ),
        migrations.RenameField(
            model_name="vote",
            old_name="createdAt",
            new_name="created",
        ),
    ]
