# Generated by Django 5.0.4 on 2024-07-03 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_vote_remove_userprofile_downvotes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="savedPosts",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="saved_posts",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_posts",
                to="core.posts",
            ),
        ),
        migrations.RemoveField(
            model_name="posts",
            name="downvotes",
        ),
        migrations.RemoveField(
            model_name="posts",
            name="upvotes",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="downvotes",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="posts",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="private_post",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="upvotes",
        ),
        migrations.AddField(
            model_name="posts",
            name="downvotes",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_downvotes",
                to="core.vote",
            ),
        ),
        migrations.AddField(
            model_name="posts",
            name="upvotes",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_upvotes",
                to="core.vote",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="downvotes",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_profile_downvotes",
                to="core.vote",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="posts",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="core.posts",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="private_post",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="private_posts",
                to="core.posts",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="upvotes",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_profile_upvotes",
                to="core.vote",
            ),
        ),
    ]
