# Generated by Django 5.0.4 on 2024-07-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_remove_userprofile_savedposts_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("argument", "argument"),
                            ("rebuttal", "rebuttal"),
                            ("comment", "comment"),
                        ],
                        default="argument",
                        max_length=10,
                    ),
                ),
                ("isPrivate", models.BooleanField(default=False)),
                ("body", models.TextField()),
                ("title", models.CharField(max_length=255)),
                ("ownerUserId", models.IntegerField(null=True)),
                ("parentId", models.IntegerField(null=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="saved_posts",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="private_post",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="posts",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="downvotes",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="upvotes",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="edits",
            field=models.ManyToManyField(related_name="edits", to="core.post"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="saved_posts",
            field=models.ManyToManyField(related_name="saved_posts", to="core.post"),
        ),
        migrations.DeleteModel(
            name="Posts",
        ),
    ]
