# Generated by Django 5.0.4 on 2024-07-08 15:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_post_remove_userprofile_saved_posts_and_more"),
        ("core", "0009_rename_joindate_userprofile_created"),
    ]

    operations = []
