# Generated by Django 5.0.4 on 2024-07-08 15:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_merge_20240708_1531"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="createdAt",
            new_name="created",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="updatedAt",
            new_name="updated",
        ),
    ]
