# Generated by Django 5.0.7 on 2024-12-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_rename_createdat_post_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="downvotes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="upvotes",
            field=models.IntegerField(default=0),
        ),
    ]
