# Generated by Django 5.0.7 on 2024-08-13 23:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_rename_createdat_post_created_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ownerUserId", models.IntegerField(null=True)),
                ("parentId", models.IntegerField(null=True)),
                ("body", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="post",
            name="type",
            field=models.CharField(
                choices=[
                    ("argument", "argument"),
                    ("rebuttal", "rebuttal"),
                    ("comment", "comment"),
                    ("suggestion", "suggestion"),
                ],
                default="argument",
                max_length=10,
            ),
        ),
    ]
