# Generated by Django 5.0.8 on 2024-08-18 04:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_report_options_alter_report_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="body",
            field=models.TextField(max_length=255, null=True),
        ),
    ]
