# Generated by Django 5.0.10 on 2024-12-09 13:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_alter_post_followers"),
        ("core", "0014_alter_report_body"),
    ]

    operations = []
