# Generated by Django 5.0.10 on 2024-12-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_merge_20241209_1339"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="options",
            field=models.JSONField(null=True),
        ),
    ]
