# Generated by Django 5.0.7 on 2024-12-31 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_alter_userprofile_created_alter_userprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="isShadow",
            field=models.BooleanField(default=False),
        ),
    ]
