# Generated by Django 5.0.7 on 2025-01-03 20:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_post_isshadow"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="isShadow",
            new_name="isPending",
        ),
    ]
