# Generated by Django 5.0.7 on 2025-01-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_rename_isshadow_post_ispending"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="parentId",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
