# Generated by Django 5.0.10 on 2025-02-09 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_alter_post_parentid"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="topParentId",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
