# Generated by Django 5.0.10 on 2025-02-11 02:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_alter_post_owneruserid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="ownerUserId",
            field=models.IntegerField(null=True),
        ),
    ]
