name: link-checker
on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: "0 0 * * *"

jobs:
  broken_link_checker_job:
    runs-on: ubuntu-latest
    name: Checking for broken links
    steps:
      - name: Checking for broken links
        id: link-report
        uses: Monstarrrr/link-checker@v0.1
        with:
          # Required:
          url: "https://rebutify.org"
          # optional:
          honorRobotExclusions: false
          ignorePatterns: "github,google"
          recursiveLinks: false # Check all URLs on all reachable pages (could take a while)
      - name: Get the result
        run: echo "${{steps.link-report.outputs.result}}"
